# Generated by Django 5.0.4 on 2024-04-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_question_student_subject_answer_quiz_question_quiz_and_more'),
        ('classroom', '0003_create_initial_subjects'),
    ]

    operations = [
    ]
